remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: PassGen
description: Minimalistic Passphrase Generation script with GUI
show_downloads: true
github:
  exe_url: https://github.com/cybardev/PassGen/releases/download/v2.0/passgen
